"""Generates components/ui/logo.tsx from the official brand SVGs. Run: python3 scripts/gen-logo.py
Only the fill colour becomes currentColor (theme); paths, transforms and viewBox are copied verbatim."""
import re

def inner(path):
    s = open(path).read()
    s = re.sub(r'<title>.*?</title>', '', s)
    body = s[s.index('>') + 1:s.rindex('</svg>')]
    body = body.replace('fill="#20231F"', 'fill="currentColor"')
    assert '#' not in re.sub(r'd="[^"]*"', '', body), 'unexpected colour in master SVG'
    vb = re.search(r'viewBox="([^"]*)"', s).group(1)
    return vb, body

vb, lock = inner('brand/VELSUNO/logo/logo-primary.svg')
vbi, iso = inner('brand/VELSUNO/logo/isotipo.svg')
w, h = (int(x) for x in vb.split()[2:])
out = f"""// GENERATED by scripts/gen-logo.py from brand/VELSUNO/logo (logo-primary.svg, isotipo.svg).
// Official master paths, unchanged; only the fill uses currentColor so light/dark follow the theme tokens.
// Do not edit by hand: never redraw the symbol or retype the wordmark.

const LOCKUP = {lock!r};
const ISOTIPO = {iso!r};

/** Horizontal lockup (symbol + wordmark). */
export function Logo({{ height = 24, className }}: {{ height?: number; className?: string }}) {{
  return (
    <svg viewBox="{vb}" height={{height}} width={{height * {w / h}}} role="img" aria-label="Velsuno" className={{className}}
      dangerouslySetInnerHTML={{{{ __html: LOCKUP }}}} />
  );
}}

/** Symbol only (Apertura). */
export function Isotipo({{ size = 24, className }}: {{ size?: number; className?: string }}) {{
  return <svg viewBox="{vbi}" width={{size}} height={{size}} role="img" aria-label="Velsuno" className={{className}} dangerouslySetInnerHTML={{{{ __html: ISOTIPO }}}} />;
}}
"""
open('components/ui/logo.tsx', 'w').write(out)
print('components/ui/logo.tsx generated')
