/** SHA-256 of synthetic test images (tests/fixtures/ai/vision) → the facts printed on them. Generated by scripts/gen-vision-fixtures.ts. */
export const VISION_FIXTURES: Record<string, Record<string, unknown>> = {};
